name: "🚀 Feature Request"
description: "Suggest new flight crash data features"
labels: ["feature-request", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        ## New Flight Crash Feature

  - type: textarea
    id: problem
    attributes:
      label: "💥 Problem"
      description: "What can't you do now?"
      placeholder: "Can't filter crashes by aircraft manufacturer"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "💡 Solution"
      description: "What feature do you want?"
      placeholder: "Add filter dropdown: Boeing, Airbus, Embraer, etc."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: "👥 Use Case"
      description: "Who benefits? Example usage?"
      placeholder: "Researchers want to analyze Boeing vs Airbus safety stats"

  - type: textarea
    id: acceptance
    attributes:
      label: "✅ Done When"
      description: "What makes it complete?"
      placeholder: |
        - Filter appears in sidebar
        - Returns correct results
        - Works on mobile

  - type: textarea
    id: data-needed
    attributes:
      label: "📊 Data Needed?"
      description: "Any new data fields required?"
      placeholder: "Aircraft manufacturer column in dataset"
